# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "vfio"
    "vfio_pci"
    "vfio_iommu_type1"
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "cryptd"
  ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [
    "kvm-amd"
    "amdgpu"
  ];
  boot.kernelParams = [
    "amd_iommu=on"
    # TODO: Check PCI ID and set
    # "vfio-pci.ids=1002:67b0,1002:aac8,144d:a80a"
  ];
  boot.extraModulePackages = [ ];
  systemd.tpm2.enable = false;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      mesa
      mesa.drivers
      rocmPackages.clr.icd
    ];
  };
  environment.variables = {
    LIBGL_DRIVERS_PATH = "${pkgs.mesa.drivers}/lib/dri";
    LIBVA_DRIVERS_PATH = "${pkgs.mesa.drivers}/lib/dri";
  };
}
