# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "cryptd"
    "igc"
  ];
  boot.initrd.kernelModules = [
    "amdgpu"
  ];
  boot.kernelModules = [
    "kvm-amd"
    "amdgpu"
    "br_netfilter"
  ];
  boot.kernelParams = [ "amd_iommu=off" ];
  boot.extraModulePackages = [ ];
  systemd.tpm2.enable = false;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      mesa
      rocmPackages.clr.icd
    ];
  };
  environment.variables = {
    LIBGL_DRIVERS_PATH = "${pkgs.mesa}/lib/dri";
    LIBVA_DRIVERS_PATH = "${pkgs.mesa}/lib/dri";
  };
}
